## Colors (One Dark)
#colors:
#  # Default colors
#  primary:
#    background: '#121319'
#    foreground: '#c6c8d1'
#
#  # Normal colors
#  normal:
#    # NOTE: Use '#131613' for the `black` color if you'd like to see
#    # black text on the background.
#    black:   '#161722'
#    red:     '#e27878'
#    green:   '#b4be82'
#    yellow:  '#e2a478'
#    blue:    '#84a0c6'
#    magenta: '#a093c7'
#    cyan:    '#89b8c2'
#    white:   '#d0d2db'
#
#  # Bright colors
#  bright:
#    black:   '#373757'
#    red:     '#f29b9e'
#    green:   '#ccdba0'
#    yellow:  '#edbe9d'
#    blue:    '#a3bee3'
#    magenta: '#c8b5e6'
#    cyan:    '#b6d8de'
#    white:   '#e9ebf5'
font:
  size: 12
  normal:
    family: Cica Nerd Font
    style: Regular
  bold:
    family: Cica Nerd Font
    style: Regular
  italic:
    family: Cica Nerd Font
    style: Regular
background_opacity: 1.0

scrolling:
    history: 10000

schemes:
  # Tokyo Night theme, based on both:
  #   https://github.com/ghifarit53/tokyonight-vim
  #   https://github.com/enkia/tokyo-night-vscode-theme
  tokyo-night: &tokyo-night
    # Default colors
    primary:
      background: '0x1a1b26'
      foreground: '0xa9b1d6'

    # Normal colors
    normal:
      black:   '0x32344a'
      red:     '0xf7768e'
      green:   '0x9ece6a'
      yellow:  '0xe0af68'
      blue:    '0x7aa2f7'
      magenta: '0xad8ee6'
      cyan:    '0x449dab'
      white:   '0x787c99'

    # Bright colors
    bright:
      black:   '0x444b6a'
      red:     '0xff7a93'
      green:   '0xb9f27c'
      yellow:  '0xff9e64'
      blue:    '0x7da6ff'
      magenta: '0xbb9af7'
      cyan:    '0x0db9d7'
      white:   '0xacb0d0'

  tokyo-night-storm: &tokyo-night-storm
    # Default colors
    primary:
      background: '0x24283b'
      foreground: '0xa9b1d6'

    # Normal colors
    normal:
      black:   '0x32344a'
      red:     '0xf7768e'
      green:   '0x9ece6a'
      yellow:  '0xe0af68'
      blue:    '0x7aa2f7'
      magenta: '0xad8ee6'
      cyan:    '0x449dab'
      white:   '0x9699a8'

    # Bright colors
    bright:
      black:   '0x444b6a'
      red:     '0xff7a93'
      green:   '0xb9f27c'
      yellow:  '0xff9e64'
      blue:    '0x7da6ff'
      magenta: '0xbb9af7'
      cyan:    '0x0db9d7'
      white:   '0xacb0d0'

# normal dark theme
#colors: *tokyo-night

# "storm" uses a lighter BG color
colors: *tokyo-night-storm
