# Colors (One Dark)
colors:
  # Default colors
  primary:
    background: '#121319'
    foreground: '#c6c8d1'

  # Normal colors
  normal:
    # NOTE: Use '#131613' for the `black` color if you'd like to see
    # black text on the background.
    black:   '#161722'
    red:     '#e27878'
    green:   '#b4be82'
    yellow:  '#e2a478'
    blue:    '#84a0c6'
    magenta: '#a093c7'
    cyan:    '#89b8c2'
    white:   '#d0d2db'

  # Bright colors
  bright:
    black:   '#373757'
    red:     '#f29b9e'
    green:   '#ccdba0'
    yellow:  '#edbe9d'
    blue:    '#a3bee3'
    magenta: '#c8b5e6'
    cyan:    '#b6d8de'
    white:   '#e9ebf5'
font:
  size: 12
  normal:
    family: Cica Nerd Font
    style: Regular
  bold:
    family: Cica Nerd Font
    style: Regular
  italic:
    family: Cica Nerd Font
    style: Regular
background_opacity: 0.8
